language: perl

services:
  - docker

env:
  global:
    - ES="localhost:9200"
    - CLIENT_VER="6_0"
    - ES_VERSION="6.0.0"
    - builddir=./dist

sudo: false

matrix:
  fast_finish: true
  
  include:
    - perl: 5.26

before_install:
  - cpanm Dist::Zilla --quiet --notest
  - '(cd $builddir && dzil authordeps --missing | cpanm --quiet --notest)'

install:
  - '(cd $builddir && dzil listdeps --missing | cpanm --quiet --notest)'
  - ./travis/run_es_docker.sh
  - ./travis/checkout_yaml_test.pl

script:
  - '(cd $builddir && dzil test --all)'
  -  dzil authordeps --missing | cpanm --quiet --notest
  - ./test/run_yaml_tests.pl
