language: perl

os: linux

services:
  - docker

env:
  global:
    - CLIENT_VER="6_0"
    - ES_VERSION="6.8.10"
    - builddir=./dist

jobs:
  fast_finish: true
  
  include:
    - perl: dev
      env: ES="http://localhost:9200"
    - perl: 5.30
      env: ES="http://localhost:9200"
    - perl: 5.30
      env: ES="https://elastic:changeme@localhost:9200"
    - perl: 5.28
      env: ES="http://localhost:9200"
    - perl: 5.28
      env: ES="https://elastic:changeme@localhost:9200"
    - perl: 5.26
      env: ES="http://localhost:9200"
    - perl: 5.26
      env: ES="https://elastic:changeme@localhost:9200"  
    - perl: 5.24
      env: ES="http://localhost:9200"
    - perl: 5.24  
      env: ES="https://elastic:changeme@localhost:9200"

  allow_failures:
    - perl: dev

before_install:
  - cpanm Dist::Zilla --quiet --notest
  - dzil authordeps --missing | cpanm --quiet --notest
  - dzil listdeps --missing | cpanm --quiet --notest
  - '(cd $builddir && dzil authordeps --missing | cpanm --quiet --notest)'
  - '(cd $builddir && dzil listdeps --missing | cpanm --quiet --notest)'

install:
  - if [[ $ES = \https* ]]; then ./travis/run_es.sh; else ./travis/run_es_oss.sh; fi
  - ./travis/checkout_yaml_test.pl

script:
  - '(cd $builddir && dzil test --all)'
  - ./test/run_yaml_tests.pl
