language: perl

services:
  - docker

env:
  global:
    - ES="localhost:9200"

sudo: false

matrix:
  fast_finish: true
  include:
    - perl: dev
      env: CLIENT_VER="6_0" ES_VERSION="6.0.0"
    - perl: 5.30
      env: CLIENT_VER="6_0" ES_VERSION="6.0.0"
    - perl: 5.28
      env: CLIENT_VER="6_0" ES_VERSION="6.0.0"
    - perl: 5.26
      env: CLIENT_VER="6_0" ES_VERSION="6.0.0"
    - perl: 5.24
      env: CLIENT_VER="6_0" ES_VERSION="6.0.0"
  allow_failures:
    - perl: dev
      env: CLIENT_VER="6_0" ES_VERSION="6.0.0"

before_install:
  - cpanm Dist::Zilla
  - cd ./dist && dzil --authordeps --missing | cpanm && dzil --listdeps --missing | cpanm
  - ./travis/run_es_docker.sh
  - ./travis/checkout_yaml_test.pl

script:
  - cd ./dist-client-6_0 && dzil test --all
  - cd ./dist-client-6_0-async && dzil test --all
