language: perl

services:
  - docker

env:
  global:
    - ES="localhost:9200"
    - CLIENT_VER="6_0"
    - ES_VERSION="6.0.0"
    - builddir=./dist

sudo: false

matrix:
  fast_finish: true
  
  include:
    - perl: dev
    - perl: 5.30
    - perl: 5.28
    - perl: 5.26
    - perl: 5.24

  allow_failures:
    - perl: dev

before_install:
  - cpanm Dist::Zilla --quiet --notest
  - dzil authordeps --missing | cpanm --quiet --notest
  - dzil listdeps --missing | cpanm --quiet --notest
  - '(cd $builddir && dzil authordeps --missing | cpanm --quiet --notest)'
  - '(cd $builddir && dzil listdeps --missing | cpanm --quiet --notest)'

install:
  - ./travis/run_es_docker.sh
  - ./travis/checkout_yaml_test.pl

script:
  - '(cd $builddir && dzil test --all)'
  - ./test/run_yaml_tests.pl
