language: perl

os: linux

services:
  - docker

env:
  global:
    - CLIENT_VER="7_0"
    - STACK_VERSION="7.3.2"
    - builddir=./dist

jobs:
  fast_finish: true
  
  include:
    - perl: 5.32
      env: TEST_SUITE="oss"
    - perl: 5.32
      env: TEST_SUITE="xpack"
    - perl: 5.30
      env: TEST_SUITE="oss"
    - perl: 5.30
      env: TEST_SUITE="xpack"
    - perl: 5.28
      env: TEST_SUITE="oss"
    - perl: 5.28
      env: TEST_SUITE="xpack"

before_install:
  - cpanm Dist::Zilla --quiet --notest
  - dzil authordeps --missing | cpanm --quiet --notest
  - dzil listdeps --missing | cpanm --quiet --notest
  - '(cd $builddir && dzil authordeps --missing | cpanm --quiet --notest)'
  - '(cd $builddir && dzil listdeps --missing | cpanm --quiet --notest)'

install:
  - ./travis/run_es.sh
  - ./travis/checkout_yaml_test.pl

script:
  - '(cd $builddir && dzil test --all)'
  - ./test/run_yaml_tests.pl
